name: VPN APK BUILDER FINAL

on:
  push:
    branches: [ "main", "Main", "Ana" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Checkout Repository
      uses: actions/checkout@v4
    
    - name: 2. Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 3. Setup Gradle (Fixed Version)
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.5' # Sürümü sabitledik ki uyumsuzluk çıkmasın

    - name: 4. Build APK
      run: |
        gradle wrapper
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon

    - name: 5. Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: VPN-App-Final
        path: app/build/outputs/apk/debug/app-debug.apk
