name: Android APK Olusturucu

on:
  push:
    branches: [ "Ana", "main", "Main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Proje Kodlarini Cek
      uses: actions/checkout@v4

    - name: Java 17 Kurulumu
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: APK Dosyasini Derle (Sistem Gradle Kullan)
      # Burada ./gradlew dosyasini aramiyoruz, direkt sistemdeki gradle'i calistiriyoruz
      run: gradle assembleDebug

    - name: APK Dosyasini Sisteme Yukle
      uses: actions/upload-artifact@v4
      with:
        name: VPN-Uygulamasi-Dosyasi
        path: app/build/outputs/apk/debug/*.apk
